
name: vm-poc-backend-fortiflex-marketplace
serviceAccount:
  create: true
  name: vm-poc-backend-fortiflex-marketplace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::228122752878:role/fortiflex-marketplace-bedrock
image:
  tag: latest
replicas: 1
containerPort: 8000
servicePort: 8000
ingressPort: 8000

env:
  SESSION_SECRET: "super-secret-string1234"
  DEBUG: "false"
  AWS_REGION: "us-east-1"
  MSSP_SECRET_NAME: "fortiflex-marketplace/mssp-master"
  DB_PATH: "/data/marketplace.db"

persistence:
  mountPath: /data
  storageClass: gp2
  size: 1Gi

ingress:
  enabled: true
  host: fortiflex-marketplace-api.fortinetcloudcse.com
  certificateArn: arn:aws:acm:us-east-1:228122752878:certificate/194f3eec-f018-47aa-be72-fec0868d16f0
  annotations:
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300
